# Generated by Django 6.0.6 on 2026-06-03 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('drivers_license_number', models.CharField(max_length=50)),
                ('drivers_license_expiry', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(help_text='Number of people it sleeps')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('damage_deposit', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rvs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('online', 'Online')], default='admin', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rentals.customer')),
                ('rv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rentals.rv')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('stripe', 'Stripe (Online)'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('etransfer', 'E-Transfer')], max_length=20)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('full', 'Full Payment'), ('damage_deposit', 'Damage Deposit'), ('refund', 'Refund')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.booking')),
            ],
        ),
    ]
