# Generated by Django 6.0.6 on 2026-06-03 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_delivery_address_booking_delivery_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('converted', 'Converted to Booking')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_delivery', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rental_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='rentals.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='rentals.rv')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
